//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlreySolutions.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TIN {
            get {
                return ((string)(this["TIN"]));
            }
            set {
                this["TIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Address2 {
            get {
                return ((string)(this["Address2"]));
            }
            set {
                this["Address2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrintVat {
            get {
                return ((bool)(this["PrintVat"]));
            }
            set {
                this["PrintVat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SERVER=localhost;DATABASE=posdbcottest;UID=admin;")]
        public string dbConnectionString1 {
            get {
                return ((string)(this["dbConnectionString1"]));
            }
            set {
                this["dbConnectionString1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Logo.png")]
        public string Logos {
            get {
                return ((string)(this["Logos"]));
            }
            set {
                this["Logos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdminPage {
            get {
                return ((bool)(this["AdminPage"]));
            }
            set {
                this["AdminPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Message3 {
            get {
                return ((string)(this["Message3"]));
            }
            set {
                this["Message3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrintTIN {
            get {
                return ((bool)(this["PrintTIN"]));
            }
            set {
                this["PrintTIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Company {
            get {
                return ((string)(this["Company"]));
            }
            set {
                this["Company"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Address1 {
            get {
                return ((string)(this["Address1"]));
            }
            set {
                this["Address1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thank you very much!")]
        public string Message1 {
            get {
                return ((string)(this["Message1"]));
            }
            set {
                this["Message1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please come again...")]
        public string Message2 {
            get {
                return ((string)(this["Message2"]));
            }
            set {
                this["Message2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrintMessage {
            get {
                return ((bool)(this["PrintMessage"]));
            }
            set {
                this["PrintMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Theme {
            get {
                return ((int)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RequireCustomerName {
            get {
                return ((bool)(this["RequireCustomerName"]));
            }
            set {
                this["RequireCustomerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.02")]
        public double InterestRate {
            get {
                return ((double)(this["InterestRate"]));
            }
            set {
                this["InterestRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddInvCalibrate {
            get {
                return ((bool)(this["AddInvCalibrate"]));
            }
            set {
                this["AddInvCalibrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POSdb.mdb")]
        public string Database {
            get {
                return ((string)(this["Database"]));
            }
            set {
                this["Database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\03. Development\\Local Dev\\PointOfSales\\Hardware_v1.10_AlamadaCoop\\Kawayanan\\bi" +
            "n\\Debug\\")]
        public string ServerPath {
            get {
                return ((string)(this["ServerPath"]));
            }
            set {
                this["ServerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int MaxPercentDiscount {
            get {
                return ((int)(this["MaxPercentDiscount"]));
            }
            set {
                this["MaxPercentDiscount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double VatPercentage {
            get {
                return ((double)(this["VatPercentage"]));
            }
            set {
                this["VatPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09175587982\r\n                ")]
        public string ContactNum {
            get {
                return ((string)(this["ContactNum"]));
            }
            set {
                this["ContactNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrintORBarcode {
            get {
                return ((bool)(this["PrintORBarcode"]));
            }
            set {
                this["PrintORBarcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-15443436,-1,-16119286,-1,-13676721,-1,-13676721,-1,-2302756,-16777216")]
        public string Theme1 {
            get {
                return ((string)(this["Theme1"]));
            }
            set {
                this["Theme1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-15790321,-1,-16777165,-65408,-16634257,-1,-16777165,-1,-16777216,-65408")]
        public string Theme2 {
            get {
                return ((string)(this["Theme2"]));
            }
            set {
                this["Theme2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-38476,-16777216,-60269,-16777216,-65281,-1,-16181,-16777216,-1,-16777216")]
        public string Theme3 {
            get {
                return ((string)(this["Theme3"]));
            }
            set {
                this["Theme3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-14803426,-1,-13296896,-32704,-7715584,-1,-12574720,-1,-32768,-16777216")]
        public string Theme4 {
            get {
                return ((string)(this["Theme4"]));
            }
            set {
                this["Theme4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-14211289,-16744193,-15987700,-16744965,-15329770,-1,-15000805,-1,-16777216,-1674" +
            "4193")]
        public string Theme5 {
            get {
                return ((string)(this["Theme5"]));
            }
            set {
                this["Theme5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\backup")]
        public string BackupPath {
            get {
                return ((string)(this["BackupPath"]));
            }
            set {
                this["BackupPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrintDuplicate {
            get {
                return ((bool)(this["PrintDuplicate"]));
            }
            set {
                this["PrintDuplicate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowReceipt {
            get {
                return ((bool)(this["ShowReceipt"]));
            }
            set {
                this["ShowReceipt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int LoadBtnSize {
            get {
                return ((int)(this["LoadBtnSize"]));
            }
            set {
                this["LoadBtnSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MaxLoadBtnCnt {
            get {
                return ((int)(this["MaxLoadBtnCnt"]));
            }
            set {
                this["MaxLoadBtnCnt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CashInSvc {
            get {
                return ((bool)(this["CashInSvc"]));
            }
            set {
                this["CashInSvc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CashOutSvc {
            get {
                return ((bool)(this["CashOutSvc"]));
            }
            set {
                this["CashOutSvc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendToOthersSvc {
            get {
                return ((bool)(this["SendToOthersSvc"]));
            }
            set {
                this["SendToOthersSvc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IntCashPickUpSvc {
            get {
                return ((bool)(this["IntCashPickUpSvc"]));
            }
            set {
                this["IntCashPickUpSvc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DomCashPickupSvc {
            get {
                return ((bool)(this["DomCashPickupSvc"]));
            }
            set {
                this["DomCashPickupSvc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemitSendSvc {
            get {
                return ((bool)(this["RemitSendSvc"]));
            }
            set {
                this["RemitSendSvc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemitCancelSvc {
            get {
                return ((bool)(this["RemitCancelSvc"]));
            }
            set {
                this["RemitCancelSvc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CashInRebate {
            get {
                return ((bool)(this["CashInRebate"]));
            }
            set {
                this["CashInRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CashOutRebate {
            get {
                return ((bool)(this["CashOutRebate"]));
            }
            set {
                this["CashOutRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendToOthersRebate {
            get {
                return ((bool)(this["SendToOthersRebate"]));
            }
            set {
                this["SendToOthersRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IntCashPickUpRebate {
            get {
                return ((bool)(this["IntCashPickUpRebate"]));
            }
            set {
                this["IntCashPickUpRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DomCashPickupRebate {
            get {
                return ((bool)(this["DomCashPickupRebate"]));
            }
            set {
                this["DomCashPickupRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemitSendRebate {
            get {
                return ((bool)(this["RemitSendRebate"]));
            }
            set {
                this["RemitSendRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemitCancelRebate {
            get {
                return ((bool)(this["RemitCancelRebate"]));
            }
            set {
                this["RemitCancelRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ChargeServiceFeeOnCancelRemittance {
            get {
                return ((bool)(this["ChargeServiceFeeOnCancelRemittance"]));
            }
            set {
                this["ChargeServiceFeeOnCancelRemittance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SmartPadalaSendSvc {
            get {
                return ((bool)(this["SmartPadalaSendSvc"]));
            }
            set {
                this["SmartPadalaSendSvc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SmartPadalaSendRebate {
            get {
                return ((bool)(this["SmartPadalaSendRebate"]));
            }
            set {
                this["SmartPadalaSendRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SmartPadalaIncashRebate {
            get {
                return ((bool)(this["SmartPadalaIncashRebate"]));
            }
            set {
                this["SmartPadalaIncashRebate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SmartPadalaIncashSvc {
            get {
                return ((bool)(this["SmartPadalaIncashSvc"]));
            }
            set {
                this["SmartPadalaIncashSvc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LoadWalletDiscount {
            get {
                return ((double)(this["LoadWalletDiscount"]));
            }
            set {
                this["LoadWalletDiscount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public double GCashResetAmount {
            get {
                return ((double)(this["GCashResetAmount"]));
            }
            set {
                this["GCashResetAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnablePrint {
            get {
                return ((bool)(this["EnablePrint"]));
            }
            set {
                this["EnablePrint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConfirmPrint {
            get {
                return ((bool)(this["ConfirmPrint"]));
            }
            set {
                this["ConfirmPrint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int HeaderFontSize {
            get {
                return ((int)(this["HeaderFontSize"]));
            }
            set {
                this["HeaderFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int NormalFontSize {
            get {
                return ((int)(this["NormalFontSize"]));
            }
            set {
                this["NormalFontSize"] = value;
            }
        }
    }
}
